site_name: Sherpa Docs
site_url: https://docs.sherpa.com

docs_dir: docs

nav:
  - About: about.md
  - Quickstart: quickstart.md
  - Architecture:
    - architecture/architecture.md
    - architecture/credentials.md
    - architecture/zero-touch-provisioning.md
  - Install / Update:
    - Install:
      - install-update/install/supported-platforms.md
      - install-update/install/automated.md
      - install-update/install/manual.md
    - Update:
      - install-update/update/sherpa.md
      - install-update/update/system.md
  - Manifest: manifest.md
  - Nodes:
    - nodes/supported-images.md
    - Arista:
      - nodes/arista/arista-veos.md
    - Aruba:
      - nodes/aruba/aruba-aoscx.md
    - BSD:
      - nodes/bsd/free-bsd.md
      - nodes/bsd/open-bsd.md
    - Cisco:
      - nodes/cisco/general.md
      - nodes/cisco/cisco-asav.md
      - nodes/cisco/cisco-cat8000v.md
      - nodes/cisco/cisco-cat9000v.md
      # - nodes/cisco/cisco-cat9800cl.md
      # - nodes/cisco/cisco-cedge.md
      - nodes/cisco/cisco-csr1000v.md
      # - nodes/cisco/cisco-fmcv.md
      # - nodes/cisco/cisco-ftdv.md
      # - nodes/cisco/cisco-ioll2.md
      # - nodes/cisco/cisco-iol.md
      # - nodes/cisco/cisco-iolserial.md
      - nodes/cisco/cisco-iosv.md
      - nodes/cisco/cisco-iosvl2.md
      - nodes/cisco/cisco-iosxrv9000.md
      - nodes/cisco/cisco-nexus9300v.md
      # - nodes/cisco/cisco-sdwanc.md
      # - nodes/cisco/cisco-sdwanm.md
      # - nodes/cisco/cisco-sdwanv.md
      # - nodes/cisco/cisco-vedge.md
    - Juniper:
      - nodes/juniper/juniper-vevolved.md
      - nodes/juniper/juniper-vrouter.md
      - nodes/juniper/juniper-vsrxv3.md
      - nodes/juniper/juniper-vswitch.md
    - Linux:
      - nodes/linux/alma-linux.md
      - nodes/linux/cumulus-linux.md
      - nodes/linux/debian-linux.md
      - nodes/linux/fedora-linux.md
      - nodes/linux/flatcar-linux.md
      - nodes/linux/opensuse-linux.md
      - nodes/linux/redhat-linux.md
      - nodes/linux/rocky-linux.md
      - nodes/linux/sonic-linux.md
      - nodes/linux/suse-linux.md
      - nodes/linux/ubuntu-linux.md
    - Mikrotik:
      - nodes/mikrotik/mikrotik-chr.md
    - Nokia:
      - nodes/nokia-srlinux.md
    - Windows:
      - nodes/windows/windows-server.md

    # - nodes/unikernels.md
  - Networking:
    - networking/management.md
    - networking/bridge.md
    - networking/isolated.md
    - networking/black-hole.md
  - Configuration:
    - configuration/sherpa.md
  - Command Reference: command-reference.md
  - Examples:
    - examples/basic.md
    - examples/clos.md
    - examples/test-servers.md
    - examples/kubernetes.md
  - Help:
    - help/libvirt.md
    - help/docker.md
    - help/troubleshooting.md

theme:
  name: material
  palette:
    - scheme: latte
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to Frapp√©

    - scheme: frappe
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to Macchiato

    # - scheme: macchiato
    #   primary: custom
    #   accent: custom
    #   toggle:
    #     icon: material/weather-partly-cloudy
    #     name: Switch to Mocha

    # - scheme: mocha
    #   primary: custom
    #   accent: custom
    #   toggle:
    #     icon: material/weather-cloudy
    #     name: Switch to Latte
  icon:
    admonition:
      note: fontawesome/solid/lightbulb

extra_css:
  - stylesheets/extra.css
  - stylesheets/table.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
