site_name: Sherpa Docs
site_url: https://docs.sherpa.com

docs_dir: docs

nav:
  - About: about.md
  - Install:
    - install/supported-platforms.md
    - install/automated.md
    - install/manual.md
  - Manifest: manifest.md
  - Usage: usage.md
  - Boxes:
    - boxes/supported-devices.md
    - boxes/virtual-machines/cisco-iosxe.md
    - boxes/containers/nokia-srlinux.md
    # - boxes/unikernels.md
  - Configuration: configuration.md
  - Troubleshooting: troubleshooting.md

theme:
  name: material
  palette:
    - scheme: latte
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to Frapp√©

    - scheme: frappe
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to Macchiato

    - scheme: macchiato
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-partly-cloudy
        name: Switch to Mocha

    - scheme: mocha
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-cloudy
        name: Switch to Latte

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
